// Services/BolPdfExporter.cs  ✅ FULL COPY/REPLACE
// Requires NuGet: QuestPDF
// Includes: Load#, Truck, Plate, Date, Time, Cities, Companies, Commodity, Mileage, Weight, Notes

using System;
using System.IO;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace OverWatchELD.Services
{
    public static class BolPdfExporter
    {
        public static void Export(
            string filePath,
            string? loadNumber,
            string? truck,
            string? licensePlate,
            string? date,
            string? time,
            string? cityOrigin,
            string? cityDestination,
            string? companyPickup,
            string? companyDropoff,
            string? commodity,
            string? mileage,
            string? weightLbs,
            string? notes)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            var bytes = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.Letter);
                    page.Margin(30);
                    page.DefaultTextStyle(x => x.FontSize(11));

                    page.Header().Column(col =>
                    {
                        col.Item().Text("BILL OF LADING (BOL)").FontSize(18).SemiBold();
                        col.Item().Text($"Generated: {DateTime.Now:MM/dd/yyyy HH:mm}")
                            .FontSize(10).FontColor(Colors.Grey.Darken2);
                    });

                    page.Content().Column(col =>
                    {
                        col.Spacing(12);

                        col.Item().Text("Load Details").SemiBold();

                        col.Item().Table(t =>
                        {
                            t.ColumnsDefinition(c => { c.RelativeColumn(); c.RelativeColumn(); });

                            Row(t, "Load Number", Clean(loadNumber));
                            Row(t, "Date", Clean(date));
                            Row(t, "Time", Clean(time));
                            Row(t, "Truck", Clean(truck));
                            Row(t, "License Plate", Clean(licensePlate));
                            Row(t, "Commodity", Clean(commodity));
                            Row(t, "Mileage", Clean(mileage));
                            Row(t, "Weight (lbs)", Clean(weightLbs));
                        });

                        col.Item().Text("Route").SemiBold();

                        col.Item().Table(t =>
                        {
                            t.ColumnsDefinition(c => { c.RelativeColumn(); c.RelativeColumn(); });

                            Row(t, "City Origin", Clean(cityOrigin));
                            Row(t, "City Destination", Clean(cityDestination));
                            Row(t, "Company Pick Up", Clean(companyPickup));
                            Row(t, "Company Drop Off", Clean(companyDropoff));
                        });

                        col.Item().PaddingTop(8).Text("Notes").SemiBold();

                        col.Item()
                            .Border(1).BorderColor(Colors.Grey.Lighten2)
                            .Padding(10).MinHeight(140)
                            .Text(string.IsNullOrWhiteSpace(notes) ? "-" : notes.Trim());
                    });

                    page.Footer().AlignCenter()
                        .Text("Generated by OverWatch ELD")
                        .FontSize(9).FontColor(Colors.Grey.Darken2);
                });
            }).GeneratePdf();

            Directory.CreateDirectory(Path.GetDirectoryName(filePath)!);
            File.WriteAllBytes(filePath, bytes);
        }

        private static void Row(TableDescriptor t, string label, string value)
        {
            t.Cell()
                .Border(1).BorderColor(Colors.Grey.Lighten2)
                .Background(Colors.Grey.Lighten4)
                .Padding(6)
                .Text(label).SemiBold();

            t.Cell()
                .Border(1).BorderColor(Colors.Grey.Lighten2)
                .Padding(6)
                .Text(value);
        }

        private static string Clean(string? v) =>
            string.IsNullOrWhiteSpace(v) ? "-" : v.Trim();
    }
}